### ISSUE TITLE
您好，我使用了您的库引入.node文件，但是问题是我require返回的是空对象

### ISSUE THREAD

**Issue by xmq1996** [toyobayashi/native-addon-loader#2]

**Comment by xmq1996** [comment]
![image](https://user-images.githubusercontent.com/29848518/80272633-c6e58580-86fd-11ea-895a-a26295e516f5.png)
![image](https://user-images.githubusercontent.com/29848518/80272636-d1a01a80-86fd-11ea-9e38-631eb0296250.png)
![image](https://user-images.githubusercontent.com/29848518/80272640-d8c72880-86fd-11ea-85a4-4bf306eb60dc.png)

**Comment by xmq1996** [comment]
![image](https://user-images.githubusercontent.com/29848518/80272669-057b4000-86fe-11ea-9b7d-8d97ea2e9698.png)

**Comment by xmq1996** [comment]
![image](https://user-images.githubusercontent.com/29848518/80272678-15931f80-86fe-11ea-979d-a55bbaeb1881.png)

**Comment by toyobayashi** [comment]
@xmq1996 麻烦贴出js是如何引入的以及生成的bundle是什么样的，或者您可以直接给我整个项目代码看一下。

如果是报错找不到 .node 文件，那就请您检查下 require 原生模块的那个 JS 文件路径是否就是在 Webpack 输出路径下，如果不是，您可能需要设置 `from` 选项去匹配正确的路径。

如果不是找不到 .node 文件，输出的代码中 require 路径是正确的但是导出空对象，那应该是原生模块本来的问题，原生代码没暴露任何接口。
